package http

import "github.com/gin-gonic/gin"

type userRoutesRegistrar struct{}

func (userRoutesRegistrar) Register(r *gin.Engine, handler *Handler, middleware *Middleware) {
	user := r.Group("/api/v1")
	user.Use(middleware.RequireUser())
	{
		user.GET("/me", handler.Me)
		user.GET("/me/user-tier", handler.MeUserTier)
		user.PATCH("/me", handler.UpdateProfile)
		user.POST("/me/password/change", handler.MePasswordChange)
		user.GET("/me/security/contacts", handler.MeSecurityContacts)
		user.POST("/me/security/email/verify-2fa", handler.MeSecurityEmailVerify2FA)
		user.POST("/me/security/email/send-code", handler.MeSecurityEmailSendCode)
		user.POST("/me/security/email/confirm", handler.MeSecurityEmailConfirm)
		user.POST("/me/security/phone/verify-2fa", handler.MeSecurityPhoneVerify2FA)
		user.POST("/me/security/phone/send-code", handler.MeSecurityPhoneSendCode)
		user.POST("/me/security/phone/confirm", handler.MeSecurityPhoneConfirm)
		user.GET("/me/security/2fa/status", handler.MeTwoFAStatus)
		user.POST("/me/security/2fa/setup", handler.MeTwoFASetup)
		user.POST("/me/security/2fa/confirm", handler.MeTwoFAConfirm)
		user.GET("/realname/status", handler.RealNameStatus)
		user.POST("/realname/verify", handler.RealNameVerify)
		user.GET("/dashboard", handler.Dashboard)
		user.GET("/goods-types", handler.GoodsTypes)
		user.GET("/catalog", handler.Catalog)
		user.GET("/plan-groups", handler.PlanGroups)
		user.GET("/packages", handler.Packages)
		user.GET("/system-images", handler.SystemImages)
		user.GET("/billing-cycles", handler.BillingCycles)
		user.GET("/payments/providers", handler.PaymentMethods)
		user.POST("/auth/logout", handler.Logout)
		user.GET("/cart", handler.CartList)
		user.POST("/cart", handler.CartAdd)
		user.DELETE("/cart", handler.CartClear)
		user.PATCH("/cart/:id", handler.CartUpdate)
		user.DELETE("/cart/:id", handler.CartDelete)
		user.POST("/orders", handler.OrderCreate)
		user.POST("/orders/items", handler.OrderCreateItems)
		user.POST("/coupons/preview", handler.CouponPreview)
		user.GET("/orders", handler.OrderList)
		user.GET("/orders/:id", handler.OrderDetail)
		user.POST("/orders/:id/pay", handler.OrderPay)
		user.POST("/orders/:id/payments", handler.OrderPayment)
		user.POST("/orders/:id/cancel", handler.OrderCancel)
		user.GET("/orders/:id/events", handler.OrderEvents)
		user.POST("/orders/:id/refresh", handler.OrderRefresh)
		user.POST("/tickets", handler.TicketCreate)
		user.GET("/tickets", handler.TicketList)
		user.GET("/tickets/:id", handler.TicketDetail)
		user.POST("/tickets/:id/messages", handler.TicketMessageCreate)
		user.POST("/tickets/:id/close", handler.TicketClose)
		user.GET("/notifications", handler.Notifications)
		user.GET("/notifications/unread-count", handler.NotificationsUnreadCount)
		user.POST("/notifications/:id/read", handler.NotificationRead)
		user.POST("/notifications/read-all", handler.NotificationReadAll)
		user.GET("/wallet", handler.WalletInfo)
		user.GET("/wallet/transactions", handler.WalletTransactions)
		user.POST("/wallet/recharge", handler.WalletRecharge)
		user.POST("/wallet/withdraw", handler.WalletWithdraw)
		user.GET("/wallet/orders", handler.WalletOrders)
		user.POST("/wallet/orders/:id/pay", handler.WalletOrderPay)
		user.POST("/wallet/orders/:id/cancel", handler.WalletOrderCancel)
		user.GET("/vps", handler.VPSList)
		user.GET("/vps/:id", handler.VPSDetail)
		user.POST("/vps/:id/refresh", handler.VPSRefresh)
		user.GET("/vps/:id/panel", handler.VPSPanel)
		user.GET("/vps/:id/monitor", handler.VPSMonitor)
		user.GET("/vps/:id/vnc", handler.VPSVNC)
		user.POST("/vps/:id/start", handler.VPSStart)
		user.POST("/vps/:id/shutdown", handler.VPSShutdown)
		user.POST("/vps/:id/reboot", handler.VPSReboot)
		user.POST("/vps/:id/reset-os", handler.VPSResetOS)
		user.POST("/vps/:id/reset-os-password", handler.VPSResetOSPassword)
		user.GET("/vps/:id/snapshots", handler.VPSSnapshots)
		user.POST("/vps/:id/snapshots", handler.VPSSnapshots)
		user.DELETE("/vps/:id/snapshots/:snapshotId", handler.VPSSnapshotDelete)
		user.POST("/vps/:id/snapshots/:snapshotId/restore", handler.VPSSnapshotRestore)
		user.GET("/vps/:id/backups", handler.VPSBackups)
		user.POST("/vps/:id/backups", handler.VPSBackups)
		user.DELETE("/vps/:id/backups/:backupId", handler.VPSBackupDelete)
		user.POST("/vps/:id/backups/:backupId/restore", handler.VPSBackupRestore)
		user.GET("/vps/:id/firewall", handler.VPSFirewallRules)
		user.POST("/vps/:id/firewall", handler.VPSFirewallRules)
		user.DELETE("/vps/:id/firewall/:ruleId", handler.VPSFirewallDelete)
		user.GET("/vps/:id/ports", handler.VPSPortMappings)
		user.POST("/vps/:id/ports", handler.VPSPortMappings)
		user.GET("/vps/:id/ports/candidates", handler.VPSPortCandidates)
		user.DELETE("/vps/:id/ports/:mappingId", handler.VPSPortMappingDelete)
		user.POST("/vps/:id/renew", handler.VPSRenewOrder)
		user.POST("/vps/:id/resize/quote", handler.VPSResizeQuote)
		user.POST("/vps/:id/resize", handler.VPSResizeOrder)
		user.POST("/vps/:id/emergency-renew", handler.VPSEmergencyRenew)
		user.POST("/vps/:id/refund", handler.VPSRefund)
	}
}
